import React, { createContext, useContext, useState, useEffect } from 'react';
import { CartItem } from './CartContext';
import { supabase } from '../lib/supabase';

export interface OrderPromo {
  code: string;
  discountValue?: number; // amount of INR saved
  isFreeShipping?: boolean;
}

export interface Order {
  id: string;
  date: string;
  paymentMethod: 'online' | 'cod';
  fulfillmentType: 'delivery' | 'pickup';
  customerData: {
    firstName: string;
    lastName: string;
    email: string;
    phone?: string;
    address?: string;
    city?: string;
    region?: string;
    zipCode?: string;
    pickupLocation?: string;
  };
  items: CartItem[];
  subtotal: number;
  deliveryFee: number;
  promos: OrderPromo[];
  total: number;
  status: 'Pending' | 'Shipped' | 'Delivered';
}

interface OrdersContextType {
  orders: Order[];
  addOrder: (order: Omit<Order, 'id' | 'date'>) => void;
  updateOrderStatus: (id: string, status: Order['status']) => void;
  updateOrder: (id: string, updatedOrder: Partial<Order>) => void;
  deleteOrder: (id: string) => void;
}

const OrdersContext = createContext<OrdersContextType | undefined>(undefined);

export const OrdersProvider: React.FC<{children: React.ReactNode}> = ({ children }) => {
  const [orders, setOrders] = useState<Order[]>([]);

  useEffect(() => {
    fetchOrders();

    // Listen for auth state changes to reload orders appropriately
    const { data: { subscription } } = supabase.auth.onAuthStateChange(() => {
       fetchOrders();
    });

    return () => subscription.unsubscribe();
  }, []);

  const fetchOrders = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      setOrders([]);
      return;
    }

    try {
      // Check if whitelisted admin
      const { data: adminData } = await supabase.from('store_admins').select('email').eq('email', user.email);
      const isAdmin = adminData && adminData.length > 0;

      let query = supabase.from('orders').select('*');
      if (!isAdmin) {
        // If not admin, only fetch orders placed by this customer
        query = query.eq('customer_id', user.id);
      }

      const { data, error } = await query.order('date', { ascending: false });

      if (error) {
        throw error;
      }

      if (data) {
        const mapped = data.map(d => ({
          id: d.id,
          date: d.date,
          paymentMethod: d.payment_method || 'online',
          fulfillmentType: d.fulfillment_type || 'delivery',
          customerData: d.customer_data,
          items: d.items,
          subtotal: d.subtotal,
          deliveryFee: d.delivery_fee,
          promos: d.promos,
          total: d.total,
          status: d.status
        }));
        setOrders(mapped);
      }
    } catch (err) {
      console.error('Error fetching orders:', err);
    }
  };

  const addOrder = async (orderData: Omit<Order, 'id' | 'date'>) => {
    // Attempt to grab current auth user (server-verified) to attach to order
    const { data: { user } } = await supabase.auth.getUser();
    
    // We do optimistic UI push so the user feels it complete instantly
    const tempId = Math.random().toString(36).substr(2, 9).toUpperCase();
    const newOrder: Order = { ...orderData, id: tempId, date: new Date().toISOString() };
    setOrders(prev => [newOrder, ...prev]);

    const { error } = await supabase.from('orders').insert([{
      customer_id: user?.id || null,
      customer_data: orderData.customerData,
      items: orderData.items,
      subtotal: orderData.subtotal,
      delivery_fee: orderData.deliveryFee,
      promos: orderData.promos,
      total: orderData.total,
      status: orderData.status,
      payment_method: orderData.paymentMethod || 'online',
      fulfillment_type: orderData.fulfillmentType || 'delivery',
    }]);

    if (error) {
       console.error('Error inserting order to Supabase:', error);
    } else {
       // Refresh to grab the real UUID generated by POSTGRES
       fetchOrders();
    }
  };

  const updateOrderStatus = async (id: string, status: Order['status']) => {
    setOrders(prev => prev.map(o => o.id === id ? { ...o, status } : o));
    await supabase.from('orders').update({ status }).eq('id', id);
  };

  const updateOrder = async (id: string, updatedOrder: Partial<Order>) => {
    setOrders(prev => prev.map(o => o.id === id ? { ...o, ...updatedOrder } : o));
    const dbUpdates: any = {};
    if (updatedOrder.customerData) dbUpdates.customer_data = updatedOrder.customerData;
    if (updatedOrder.items) dbUpdates.items = updatedOrder.items;
    if (updatedOrder.subtotal !== undefined) dbUpdates.subtotal = updatedOrder.subtotal;
    if (updatedOrder.deliveryFee !== undefined) dbUpdates.delivery_fee = updatedOrder.deliveryFee;
    if (updatedOrder.promos) dbUpdates.promos = updatedOrder.promos;
    if (updatedOrder.total !== undefined) dbUpdates.total = updatedOrder.total;
    if (updatedOrder.status) dbUpdates.status = updatedOrder.status;

    await supabase.from('orders').update(dbUpdates).eq('id', id);
  };

  const deleteOrder = async (id: string) => {
    setOrders(prev => prev.filter(o => o.id !== id));
    await supabase.from('orders').delete().eq('id', id);
  };

  return (
    <OrdersContext.Provider value={{ orders, addOrder, updateOrderStatus, updateOrder, deleteOrder }}>
      {children}
    </OrdersContext.Provider>
  );
};

export const useOrders = () => {
  const context = useContext(OrdersContext);
  if (context === undefined) throw new Error('useOrders must be used within an OrdersProvider');
  return context;
};
